name: CI

on:
  schedule:
    - cron: '0 0 * * *' # Every day at 00:00 UTC
  workflow_dispatch:

env:
  WRAPPER_UPGRADE_GIT_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  Upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            upgradeGradleWrapperAll
            upgradeMavenWrapperAll
