name: Upgrade Gradle and Maven Wrappers

on:
  schedule:
    - cron: '0 0 * * *' # Every day at 00:00 UTC
  workflow_dispatch:

env:
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
  WRAPPER_UPGRADE_GIT_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Set up Git
        run: |
          git config --global user.name "JUnit Team"
          git config --global user.email "team@junit.org"
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: upgradeGradleWrapperAll
  Maven:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Set up Git
        run: |
          git config --global user.name "JUnit Team"
          git config --global user.email "team@junit.org"
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: upgradeMavenWrapperAll --info
